# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'integrated.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_integrated(object):
    def setupUi(self, integrated):
        integrated.setObjectName("integrated")
        integrated.resize(647, 539)
        self.tabWidget = QtWidgets.QTabWidget(integrated)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 781, 631))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.pushButton = QtWidgets.QPushButton(self.tab)
        self.pushButton.setGeometry(QtCore.QRect(120, 150, 321, 101))
        self.pushButton.setObjectName("pushButton")
        self.tabWidget.addTab(self.tab, "")

        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tableWidget = QtWidgets.QTableWidget(self.tab_2)
        self.tableWidget.setGeometry(QtCore.QRect(150, 130, 351, 271))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(2)
        self.tableWidget.setRowCount(1)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        self.tabWidget.addTab(self.tab_2, "")

        self.retranslateUi(integrated)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(integrated)

    def retranslateUi(self, integrated):
        _translate = QtCore.QCoreApplication.translate
        integrated.setWindowTitle(_translate("integrated", "integrated"))
        self.pushButton.setText(_translate("integrated", "PushButton"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("integrated", "Tab 1"))
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("integrated", "Row1"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("integrated", "New Column"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("integrated", "Column2"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("integrated", "Tab 2"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    integrated = QtWidgets.QWidget()
    ui = Ui_integrated()
    ui.setupUi(integrated)
    integrated.show()
    sys.exit(app.exec_())
