from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_NeutronPy(object):
    def setupUi(self, NeutronPy):
        NeutronPy.setObjectName("NeutronPy")
        NeutronPy.resize(824, 603)
        self.centralwidget = QtWidgets.QWidget(NeutronPy)
        self.centralwidget.setObjectName("centralwidget")
        self.ElementGUI = QtWidgets.QFrame(self.centralwidget)
        self.ElementGUI.setGeometry(QtCore.QRect(10, 10, 501, 321))
        self.ElementGUI.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.ElementGUI.setFrameShadow(QtWidgets.QFrame.Raised)
        self.ElementGUI.setObjectName("ElementGUI")
        self.ElementGUI_Image = QtWidgets.QFrame(self.ElementGUI)
        self.ElementGUI_Image.setGeometry(QtCore.QRect(19, 19, 241, 221))
        self.ElementGUI_Image.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.ElementGUI_Image.setFrameShadow(QtWidgets.QFrame.Raised)
        self.ElementGUI_Image.setObjectName("ElementGUI_Image")
        self.horizontalScrollBar = QtWidgets.QScrollBar(self.ElementGUI_Image)
        self.horizontalScrollBar.setGeometry(QtCore.QRect(0, 200, 241, 16))
        self.horizontalScrollBar.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalScrollBar.setObjectName("horizontalScrollBar")
        self.line_17 = QtWidgets.QFrame(self.ElementGUI_Image)
        self.line_17.setGeometry(QtCore.QRect(230, -10, 20, 231))
        self.line_17.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_17.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_17.setObjectName("line_17")
        self.line_18 = QtWidgets.QFrame(self.ElementGUI_Image)
        self.line_18.setGeometry(QtCore.QRect(0, 210, 241, 16))
        self.line_18.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_18.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_18.setObjectName("line_18")
        self.line_9 = QtWidgets.QFrame(self.ElementGUI)
        self.line_9.setGeometry(QtCore.QRect(0, 0, 16, 321))
        self.line_9.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_9.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_9.setObjectName("line_9")
        self.line_10 = QtWidgets.QFrame(self.ElementGUI)
        self.line_10.setGeometry(QtCore.QRect(490, 0, 16, 321))
        self.line_10.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_10.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_10.setObjectName("line_10")
        self.line_13 = QtWidgets.QFrame(self.ElementGUI)
        self.line_13.setGeometry(QtCore.QRect(10, 0, 491, 16))
        self.line_13.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_13.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_13.setObjectName("line_13")
        self.line_14 = QtWidgets.QFrame(self.ElementGUI)
        self.line_14.setGeometry(QtCore.QRect(10, 310, 491, 16))
        self.line_14.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_14.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_14.setObjectName("line_14")
        self.line_19 = QtWidgets.QFrame(self.ElementGUI)
        self.line_19.setGeometry(QtCore.QRect(10, 20, 16, 221))
        self.line_19.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_19.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_19.setObjectName("line_19")
        self.line_20 = QtWidgets.QFrame(self.ElementGUI)
        self.line_20.setGeometry(QtCore.QRect(20, 20, 241, 16))
        self.line_20.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_20.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_20.setObjectName("line_20")
        self.Beamline = QtWidgets.QFrame(self.centralwidget)
        self.Beamline.setGeometry(QtCore.QRect(10, 340, 391, 221))
        self.Beamline.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Beamline.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Beamline.setObjectName("Beamline")
        self.line = QtWidgets.QFrame(self.Beamline)
        self.line.setGeometry(QtCore.QRect(0, 0, 16, 221))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_6 = QtWidgets.QFrame(self.Beamline)
        self.line_6.setGeometry(QtCore.QRect(10, 210, 381, 20))
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.SpectrumGraph = QtWidgets.QFrame(self.centralwidget)
        self.SpectrumGraph.setGeometry(QtCore.QRect(530, 10, 281, 321))
        self.SpectrumGraph.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.SpectrumGraph.setFrameShadow(QtWidgets.QFrame.Raised)
        self.SpectrumGraph.setObjectName("SpectrumGraph")
        self.line_15 = QtWidgets.QFrame(self.SpectrumGraph)
        self.line_15.setGeometry(QtCore.QRect(0, 310, 281, 16))
        self.line_15.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_15.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_15.setObjectName("line_15")
        self.line_16 = QtWidgets.QFrame(self.SpectrumGraph)
        self.line_16.setGeometry(QtCore.QRect(0, 0, 281, 16))
        self.line_16.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_16.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_16.setObjectName("line_16")
        self.Material = QtWidgets.QFrame(self.centralwidget)
        self.Material.setGeometry(QtCore.QRect(410, 340, 401, 221))
        self.Material.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Material.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Material.setObjectName("Material")
        self.line_3 = QtWidgets.QFrame(self.Material)
        self.line_3.setGeometry(QtCore.QRect(0, 0, 16, 221))
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.line_4 = QtWidgets.QFrame(self.Material)
        self.line_4.setGeometry(QtCore.QRect(390, 0, 16, 221))
        self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.line_7 = QtWidgets.QFrame(self.Material)
        self.line_7.setGeometry(QtCore.QRect(10, 0, 391, 20))
        self.line_7.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.line_8 = QtWidgets.QFrame(self.Material)
        self.line_8.setGeometry(QtCore.QRect(10, 210, 391, 20))
        self.line_8.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(390, 340, 16, 221))
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.line_5 = QtWidgets.QFrame(self.centralwidget)
        self.line_5.setGeometry(QtCore.QRect(20, 330, 381, 20))
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.line_12 = QtWidgets.QFrame(self.centralwidget)
        self.line_12.setGeometry(QtCore.QRect(800, 10, 16, 321))
        self.line_12.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_12.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_12.setObjectName("line_12")
        self.line_11 = QtWidgets.QFrame(self.centralwidget)
        self.line_11.setGeometry(QtCore.QRect(520, 10, 16, 321))
        self.line_11.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_11.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_11.setObjectName("line_11")
        NeutronPy.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(NeutronPy)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 824, 21))
        self.menubar.setObjectName("menubar")
        NeutronPy.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(NeutronPy)
        self.statusbar.setObjectName("statusbar")
        NeutronPy.setStatusBar(self.statusbar)

        self.retranslateUi(NeutronPy)
        QtCore.QMetaObject.connectSlotsByName(NeutronPy)

    def retranslateUi(self, NeutronPy):
        _translate = QtCore.QCoreApplication.translate
        NeutronPy.setWindowTitle(_translate("NeutronPy", "NeutronPy"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    NeutronPy = QtWidgets.QMainWindow()
    ui = Ui_NeutronPy()
    ui.setupUi(NeutronPy)
    NeutronPy.show()
    sys.exit(app.exec_())
