# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_NeutronPytest1(object):
    def setupUi(self, NeutronPytest1):
        NeutronPytest1.setObjectName("NeutronPytest1")
        NeutronPytest1.resize(729, 507)
        self.frame = QtWidgets.QFrame(NeutronPytest1)
        self.frame.setGeometry(QtCore.QRect(20, 30, 381, 251))
        self.frame.setObjectName("frame")
        self.frame_5 = QtWidgets.QFrame(self.frame)
        self.frame_5.setGeometry(QtCore.QRect(30, 20, 221, 181))
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.horizontalScrollBar = QtWidgets.QScrollBar(self.frame_5)
        self.horizontalScrollBar.setGeometry(QtCore.QRect(0, 160, 221, 17))
        self.horizontalScrollBar.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalScrollBar.setObjectName("horizontalScrollBar")
        self.comboBox = QtWidgets.QComboBox(self.frame)
        self.comboBox.setGeometry(QtCore.QRect(10, 200, 261, 22))
        self.comboBox.setObjectName("comboBox")
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.frame)
        self.textBrowser_2.setGeometry(QtCore.QRect(60, 200, 181, 21))
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.frame_6 = QtWidgets.QFrame(self.frame)
        self.frame_6.setGeometry(QtCore.QRect(279, 0, 101, 251))
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.frame_7 = QtWidgets.QFrame(self.frame_6)
        self.frame_7.setGeometry(QtCore.QRect(0, 0, 101, 31))
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.textBrowser_3 = QtWidgets.QTextBrowser(self.frame_7)
        self.textBrowser_3.setGeometry(QtCore.QRect(0, 0, 101, 31))
        self.textBrowser_3.setObjectName("textBrowser_3")
        self.frame_8 = QtWidgets.QFrame(self.frame_6)
        self.frame_8.setGeometry(QtCore.QRect(0, 30, 101, 61))
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.textBrowser_4 = QtWidgets.QTextBrowser(self.frame_8)
        self.textBrowser_4.setGeometry(QtCore.QRect(0, 0, 51, 81))
        self.textBrowser_4.setObjectName("textBrowser_4")
        self.textEdit = QtWidgets.QTextEdit(self.frame_8)
        self.textEdit.setGeometry(QtCore.QRect(50, 0, 51, 31))
        self.textEdit.setObjectName("textEdit")
        self.textEdit_2 = QtWidgets.QTextEdit(self.frame_8)
        self.textEdit_2.setGeometry(QtCore.QRect(50, 30, 51, 31))
        self.textEdit_2.setObjectName("textEdit_2")
        self.frame_9 = QtWidgets.QFrame(self.frame_6)
        self.frame_9.setGeometry(QtCore.QRect(0, 90, 101, 91))
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.textBrowser_5 = QtWidgets.QTextBrowser(self.frame_9)
        self.textBrowser_5.setGeometry(QtCore.QRect(0, 0, 51, 91))
        self.textBrowser_5.setObjectName("textBrowser_5")
        self.textEdit_3 = QtWidgets.QTextEdit(self.frame_9)
        self.textEdit_3.setGeometry(QtCore.QRect(50, 0, 51, 31))
        self.textEdit_3.setObjectName("textEdit_3")
        self.textEdit_4 = QtWidgets.QTextEdit(self.frame_9)
        self.textEdit_4.setGeometry(QtCore.QRect(50, 30, 51, 31))
        self.textEdit_4.setObjectName("textEdit_4")
        self.textEdit_5 = QtWidgets.QTextEdit(self.frame_9)
        self.textEdit_5.setGeometry(QtCore.QRect(50, 60, 51, 31))
        self.textEdit_5.setObjectName("textEdit_5")
        self.textBrowser_6 = QtWidgets.QTextBrowser(self.frame_6)
        self.textBrowser_6.setGeometry(QtCore.QRect(0, 180, 51, 71))
        self.textBrowser_6.setObjectName("textBrowser_6")
        self.textEdit_6 = QtWidgets.QTextEdit(self.frame_6)
        self.textEdit_6.setGeometry(QtCore.QRect(50, 180, 51, 71))
        self.textEdit_6.setObjectName("textEdit_6")
        self.graphicsView_6 = QtWidgets.QGraphicsView(self.frame_6)
        self.graphicsView_6.setGeometry(QtCore.QRect(100, 0, 321, 251))
        self.graphicsView_6.setObjectName("graphicsView_6")
        self.graphicsView_2 = QtWidgets.QGraphicsView(self.frame)
        self.graphicsView_2.setGeometry(QtCore.QRect(0, 0, 256, 192))
        self.graphicsView_2.setObjectName("graphicsView_2")
        self.graphicsView_3 = QtWidgets.QGraphicsView(self.frame)
        self.graphicsView_3.setGeometry(QtCore.QRect(0, 0, 381, 251))
        self.graphicsView_3.setObjectName("graphicsView_3")
        self.graphicsView_2.raise_()
        self.graphicsView_3.raise_()
        self.frame_5.raise_()
        self.comboBox.raise_()
        self.textBrowser_2.raise_()
        self.frame_6.raise_()
        self.frame_2 = QtWidgets.QFrame(NeutronPytest1)
        self.frame_2.setGeometry(QtCore.QRect(420, 30, 291, 251))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.graphicsView_7 = QtWidgets.QGraphicsView(self.frame_2)
        self.graphicsView_7.setGeometry(QtCore.QRect(0, 0, 291, 251))
        self.graphicsView_7.setObjectName("graphicsView_7")
        self.textBrowser_13 = QtWidgets.QTextBrowser(self.frame_2)
        self.textBrowser_13.setGeometry(QtCore.QRect(190, 0, 101, 31))
        self.textBrowser_13.setObjectName("textBrowser_13")
        self.textBrowser_14 = QtWidgets.QTextBrowser(self.frame_2)
        self.textBrowser_14.setGeometry(QtCore.QRect(190, 30, 61, 51))
        self.textBrowser_14.setObjectName("textBrowser_14")
        self.textBrowser_15 = QtWidgets.QTextBrowser(self.frame_2)
        self.textBrowser_15.setGeometry(QtCore.QRect(190, 80, 101, 41))
        self.textBrowser_15.setObjectName("textBrowser_15")
        self.textBrowser_16 = QtWidgets.QTextBrowser(self.frame_2)
        self.textBrowser_16.setGeometry(QtCore.QRect(190, 120, 101, 41))
        self.textBrowser_16.setObjectName("textBrowser_16")
        self.textEdit_7 = QtWidgets.QTextEdit(self.frame_2)
        self.textEdit_7.setGeometry(QtCore.QRect(250, 30, 41, 51))
        self.textEdit_7.setObjectName("textEdit_7")
        self.textEdit_8 = QtWidgets.QTextEdit(self.frame_2)
        self.textEdit_8.setGeometry(QtCore.QRect(250, 80, 41, 41))
        self.textEdit_8.setObjectName("textEdit_8")
        self.textEdit_9 = QtWidgets.QTextEdit(self.frame_2)
        self.textEdit_9.setGeometry(QtCore.QRect(250, 120, 41, 41))
        self.textEdit_9.setObjectName("textEdit_9")
        self.textBrowser_17 = QtWidgets.QTextBrowser(self.frame_2)
        self.textBrowser_17.setGeometry(QtCore.QRect(190, 160, 101, 91))
        self.textBrowser_17.setObjectName("textBrowser_17")
        self.textBrowser_18 = QtWidgets.QTextBrowser(self.frame_2)
        self.textBrowser_18.setGeometry(QtCore.QRect(0, 0, 191, 31))
        self.textBrowser_18.setObjectName("textBrowser_18")
        self.textBrowser_19 = QtWidgets.QTextBrowser(self.frame_2)
        self.textBrowser_19.setGeometry(QtCore.QRect(0, 120, 191, 31))
        self.textBrowser_19.setObjectName("textBrowser_19")
        self.frame_3 = QtWidgets.QFrame(NeutronPytest1)
        self.frame_3.setGeometry(QtCore.QRect(20, 300, 321, 191))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.graphicsView_4 = QtWidgets.QGraphicsView(self.frame_3)
        self.graphicsView_4.setGeometry(QtCore.QRect(0, 0, 321, 191))
        self.graphicsView_4.setObjectName("graphicsView_4")
        self.textBrowser_7 = QtWidgets.QTextBrowser(self.frame_3)
        self.textBrowser_7.setGeometry(QtCore.QRect(0, 0, 331, 41))
        self.textBrowser_7.setObjectName("textBrowser_7")
        self.textBrowser_8 = QtWidgets.QTextBrowser(self.frame_3)
        self.textBrowser_8.setGeometry(QtCore.QRect(0, 40, 321, 31))
        self.textBrowser_8.setObjectName("textBrowser_8")
        self.frame_4 = QtWidgets.QFrame(NeutronPytest1)
        self.frame_4.setGeometry(QtCore.QRect(360, 300, 351, 191))
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.graphicsView_5 = QtWidgets.QGraphicsView(self.frame_4)
        self.graphicsView_5.setGeometry(QtCore.QRect(0, 0, 351, 191))
        self.graphicsView_5.setObjectName("graphicsView_5")
        self.textBrowser_9 = QtWidgets.QTextBrowser(self.frame_4)
        self.textBrowser_9.setGeometry(QtCore.QRect(0, 0, 351, 51))
        self.textBrowser_9.setObjectName("textBrowser_9")
        self.textBrowser_10 = QtWidgets.QTextBrowser(self.frame_4)
        self.textBrowser_10.setGeometry(QtCore.QRect(0, 50, 351, 31))
        self.textBrowser_10.setObjectName("textBrowser_10")
        self.textBrowser_11 = QtWidgets.QTextBrowser(self.frame_4)
        self.textBrowser_11.setGeometry(QtCore.QRect(0, 80, 351, 31))
        self.textBrowser_11.setObjectName("textBrowser_11")
        self.textBrowser_12 = QtWidgets.QTextBrowser(self.frame_4)
        self.textBrowser_12.setGeometry(QtCore.QRect(0, 110, 351, 31))
        self.textBrowser_12.setObjectName("textBrowser_12")
        self.textBrowser = QtWidgets.QTextBrowser(NeutronPytest1)
        self.textBrowser.setGeometry(QtCore.QRect(20, 0, 61, 31))
        self.textBrowser.setObjectName("textBrowser")
        self.frame_2.raise_()
        self.frame_3.raise_()
        self.frame_4.raise_()
        self.textBrowser.raise_()
        self.frame.raise_()

        self.retranslateUi(NeutronPytest1)
        QtCore.QMetaObject.connectSlotsByName(NeutronPytest1)

    def retranslateUi(self, NeutronPytest1):
        _translate = QtCore.QCoreApplication.translate
        NeutronPytest1.setWindowTitle(_translate("NeutronPytest1", "NeutronPytest1"))
        self.textBrowser_2.setHtml(_translate("NeutronPytest1", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:7pt;\">Folder Selection</span></p></body></html>"))
        self.textBrowser_3.setHtml(_translate("NeutronPytest1", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-style:italic;\">Options</span></p></body></html>"))
        self.textBrowser_4.setHtml(_translate("NeutronPytest1", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">X-max:</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Y-max:</p></body></html>"))
        self.textEdit.setHtml(_translate("NeutronPytest1", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.textBrowser_5.setHtml(_translate("NeutronPytest1", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">X-min:</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Y-min:</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Z:</p></body></html>"))
        self.textBrowser_6.setHtml(_translate("NeutronPytest1", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:6pt;\">Brightness</span></p></body></html>"))
        self.textBrowser_13.setHtml(_translate("NeutronPytest1", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-style:italic;\">Options</span></p></body></html>"))
        self.textBrowser_14.setHtml(_translate("NeutronPytest1", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Units of Index</p></body></html>"))
        self.textBrowser_15.setHtml(_translate("NeutronPytest1", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">TOF:</p></body></html>"))
        self.textBrowser_16.setHtml(_translate("NeutronPytest1", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Energy:</p></body></html>"))
        self.textBrowser_18.setHtml(_translate("NeutronPytest1", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt;\">Actual Spectrum</span></p></body></html>"))
        self.textBrowser_19.setHtml(_translate("NeutronPytest1", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt;\">Quick Fit</span></p></body></html>"))
        self.textBrowser_7.setHtml(_translate("NeutronPytest1", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt;\">Beam Line Characteristics</span></p></body></html>"))
        self.textBrowser_8.setHtml(_translate("NeutronPytest1", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Beam Path Length</p></body></html>"))
        self.textBrowser_9.setHtml(_translate("NeutronPytest1", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt;\">Material Characteristics</span></p></body></html>"))
        self.textBrowser_10.setHtml(_translate("NeutronPytest1", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Select Materials</p></body></html>"))
        self.textBrowser_11.setHtml(_translate("NeutronPytest1", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Concentration of A:      Thickness:    Density:</p></body></html>"))
        self.textBrowser_12.setHtml(_translate("NeutronPytest1", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Concentration of B:      Thickness:    Density:</p></body></html>"))
        self.textBrowser.setHtml(_translate("NeutronPytest1", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">NeutronPy</p></body></html>"))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    NeutronPy = QtWidgets.QMainWindow()
    ui = Ui_NeutronPytest1()
    ui.setupUi(NeutronPy)
    NeutronPy.show()
    sys.exit(app.exec_())
